### ISSUE TITLE
[Bug] Mac OS Safari에서 SWJudger login 페이지 접속시 아이디 / 비밀번호 입력 불가능

### ISSUE THREAD

**Issue by HwanwoongKim** [cbnusw/sw-judger#6]
메인 페이지에서 아이디 / 비밀번호는 입력되나, 로그인 페이지에서 입력은 되지 않습니다.

https://github.com/cbnusw/sw-judger/blame/main/judger-frontend/projects/main/src/app/pages/account-pages/login-page/login-page.component.html

이곳에서 10, 28번째 Line에 있는
<input class = 'none-select'   에서 class property를 지우면 Safari에서 입력되는 것을 확인했습니다.

감사합니다.

**Comment by developersung13** [comment]
웹 프로젝트 변경으로 인해 해당 이슈를 `closing` 처리합니다.

**Comment by developersung13** [comment]
웹 프로젝트 변경으로 인해 해당 이슈를 `closing` 처리합니다.
